[book]
authors = ["Dylan Owen"]
language = "en"
multilingual = false
src = "src"
title = "Sample"

[preprocessor.graphviz]
copy-css = true
copy-js = true

[preprocessor.d2-interactive]
copy-css = true
copy-js = true

[output.markdown]

[output.html]
additional-css = ["css/svg.css"]
additional-js = ["js/svg.js"]
